### ISSUE TITLE
Access the AOP ontology using Protégé or online?

### ISSUE THREAD

**Issue by lrieswijk** [DataSciBurgoon/aop-ontology#2]
Is there a way to open the AOP ontology in Protégé? If I download the aop owl file it doesn't work. It would be nice to access the ontology either locally or online. Thanks!

**Comment by DataSciBurgoon** [comment]
The ontology was designed in Protege, and I currently make updates to it in Protege. Without seeing the errors you're getting I'm not sure what's going on, but you should probably download the entire project directory and try opening again. My guess is that it's looking for some of the imported ontologies and it can't find them if you only downloaded the owl file. Let me know if that helps.
