### ISSUE TITLE
The HP ontology owl:import is broken

### ISSUE THREAD

**Issue by egonw** [DataSciBurgoon/aop-ontology#4]
The link in the import no longer works, and the following patch uses the latest version instead:

https://github.com/DataSciBurgoon/aop-ontology/compare/master...enanomapper:patch/hpoUpdate?expand=1

But you may want to use a specific version, which is why I did not create a pull request (yet).

**Comment by DataSciBurgoon** [comment]
Thanks -- making correction now.

**Comment by DataSciBurgoon** [comment]
Pushed updated.

**Comment by cmungall** [comment]
Best to use the official PURL, see #6
